### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by cameronmaske** [joextodd/pysoundio#27]
Hey there, 

Any interested in pysoundio including Windows support?

I'm happy to help contribute, but would really appreciate guidance on how to set it up.

I've tried modifying `setup.py` locally to point it's `library_dirs` to a local folder with Windows binaries from http://libsound.io/. I renamed `libsoundio.a` -> `libsoundio.lib` to python to find the library when running `python setup.py install`.

The install completed, but now running any of the code, it fails to import the DLL. 
```
Traceback (most recent call last):
  File ".\examples\devices.py", line 8, in <module>
    from pysoundio import PySoundIo, SoundIoFormat
  File "C:\Users\Cameron\.virtualenvs\Dev-Zr-pp-Ey\lib\site-packages\pysoundio-1.0.0-py3.6-win-amd64.egg\pysoundio\__init__.py", line 30, in <module>
  File "C:\Users\Cameron\.virtualenvs\Dev-Zr-pp-Ey\lib\site-packages\pysoundio-1.0.0-py3.6-win-amd64.egg\pysoundio\__init__.py", line 28, in <module>
  File "C:\Users\Cameron\.virtualenvs\Dev-Zr-pp-Ey\lib\site-packages\pysoundio-1.0.0-py3.6-win-amd64.egg\_soundiox.py",
line 7, in <module>
  File "C:\Users\Cameron\.virtualenvs\Dev-Zr-pp-Ey\lib\site-packages\pysoundio-1.0.0-py3.6-win-amd64.egg\_soundiox.py",
line 6, in __bootstrap__
  File "C:\Users\Cameron\.virtualenvs\Dev-Zr-pp-Ey\lib\imp.py", line 356, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.
```

Any guidance/knowledge on steps forward would be much appreciated!

**Comment by joextodd** [comment]
Hey, 

Yes Windows is a bit of a PITA when it comes to debugging DLL import errors.

In other projects in the past, I seem to recall having to add `runtime_library_dirs` to the `Extension` in `setup.py` as well.

Would definitely like to include Windows support though! Will try look into it next time I have access to a Windows machine.

**Comment by joextodd** [comment]
@cameronmaske OK I think what you need to do is rename the `.dll.a` to `.lib` and it should work!

Would appreciate your input on what the general practises are for installing libraries like this on Windows. Do people just copy and paste to `C:\Windows\System32` ?

**Comment by cameronmaske** [comment]
@joextodd Renaming the `.dll.a` to `.lib` does the trick! 

I'm not really sure what the general practices are for installing libs on Windows, it's a fairly new area for me. 

I put together a branch that includes the binaries as part of the [pysoundio package](https://github.com/cameronmaske/pysoundio/tree/windows/pysoundio/libs/win) and point setup.py to the [files library locally](https://github.com/cameronmaske/pysoundio/pull/1/files#diff-2eeaed663bd0d25b7e608891384b7298R24).
Then will attempt to modify the [`$PATH` to include the `.dll` at runtime](https://github.com/cameronmaske/pysoundio/pull/1/files#diff-cb6965e211724e4166bbb869910c1fe2R42).

I'm really not sure if this is an awful hack, or an acceptable approach, so I welcome any comments/thoughts.

**Comment by joextodd** [comment]
I do quite like the idea of bundling in static libraries with the package, it would remove the need to install the library yourself. 

If this is the way to go I would like to include builds for all architectures - macOS, Win32, Win64, Linux and Raspbian.

**Comment by cameronmaske** [comment]
We could do something similar to what [SoundFile](https://github.com/bastibe/SoundFile) does for libsndfile and host the [built binaries](https://github.com/bastibe/libsndfile-binaries/tree/fcf9ddc651ddcbdbf661594f0ede09c70076acb8). However, they don't do it for Linux (I wonder if there is a specific reason why).

**Comment by joextodd** [comment]
Interesting. The only issue I could see with this is that some people might want it compiled with JACK or PulseAudio enabled and others not. It gives a bit more versatility and anyone tackling audio io will be capable of compiling from source..

**Comment by cameronmaske** [comment]
Possibly! The barrier to install for Linux and OSX (a single `brew` or `apt-get` command) seems a lot lower than for Windows. There also seem to be much more flavours of Linux, so maybe that's a factor. 

I've started putting together some tooling to [compile the different versions on this repo](https://github.com/cameronmaske/libsoundio-binaries). It's currently only Windows, but I'll do OSX, Linux/Raspbian next. 

With the `$PATH` patch, by appending to the end of the `$PATH`, prior installs should take precedent, which would still allow users to use their own custom compiles if they prefer.

**Comment by joextodd** [comment]
I have compiled for Linux on Ubuntu before and it does work for lots of flavours of Linux, provided you use as older version of Ubuntu as possible - otherwise you get backwards compatibility issues when linking with glibc on older platforms.

I have added a commit that will check for the binary download at `C:\ProgramData\libsoundio` and will rename the files accordingly, but you're right - support for compiled and custom binaries would make the package better!

**Comment by pearsonkyle** [comment]
I've been trying to install this library for windows and have run into the following issue. 

I've moved the windows binaries from this page: http://libsound.io/#releases into my `C:/ProgramData/libsoundio` folder and then I try to run: `pip install pysoundio`

and run into the following error: 

`       Creating library build\temp.win-amd64-3.6\Release\pysoundio\_soundiox.cp36-win_amd64.lib and object build\temp.win-amd64-3.6\Release\pysoundio\_soundiox.cp36-win_amd64.exp
    _soundiox.obj : error LNK2001: unresolved external symbol soundio_outstream_set_volume
    build\lib.win-amd64-3.6\_soundiox.cp36-win_amd64.pyd : fatal error LNK1120: 1 unresolved externals
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.10.25017\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120 `

Any idea on how to solve it?

**Comment by joextodd** [comment]
@pearsonkyle  unfortunately libsoundio does not export the version number in the header files, so I have had to do some hacky way of checking the version. 

This function is new to v2.0.0, which of course doesn't have a Windows binary built yet. So you have two options. 

1. Build libsoundio v2.0.0 from source
2. Clone this repo, comment out all of the `outstream_set_volume` bits from `_soundio.c`, `_soundio.h` and `pysoundio.py`. Then try rebuild with `python setup.py install`

**Comment by cameronmaske** [comment]
@pearsonkyle I have some binaries built for Windows based on 2.0.0 that may help!
[You can download them here](https://github.com/cameronmaske/libsoundio-binaries/tree/master/win)

**Comment by pearsonkyle** [comment]
@joextodd Thank you for your help! I commented out those lines and was able to install it successfully. 
@cameronmaske  thank you for those binaries, they worked. 

One minor issue, I placed the binaries in my `C:\ProgramData\libsoundio\x86_64` directory however the code kept saying to install libsoundio and it could not run this line `import _soundiox as soundio` in `__init__.py`. I tried adding the path to the binaries to my `PATH` variable and even to my `PYTHONPATH` neither worked. 

Things worked when I moved the binaries into the same directory as the `examples/` folder and ran an example. So it works...I just have the binaries in the same directory I'm working in, which is fine for now.

**Comment by joextodd** [comment]
@pearsonkyle that's great, almost there. I'm still working on the above suggestion from @cameronmaske to bundle in the libraries automatically. Could you try something out for me?

Edit the `soundio` definition in `setup.py` and then try reinstall. It might need the `runtime_library_dirs` setting..

```
soundio = Extension('_soundiox',
                    sources=['pysoundio/_soundiox.c'],
                    include_dirs=include_dirs,
                    library_dirs=library_dirs,
                    runtime_library_dirs=library_dirs,
                    libraries=['soundio'])
```

**Comment by pearsonkyle** [comment]
@joextodd I added that to `setup.py` and it installs successfully and `library_dirs` points to the correct path

Everything works fine now! Just needed to add `C:\ProgramData\libsoundio\x86_64` to my `PATH` variable and restart my computer

**Comment by joextodd** [comment]
@cameronmaske I finally got around to integrating your Windows builds into the package, although I don't have a Windows machine here. Would be much appreciated if you could install `pysoundio==2.0.0rc1` and see if the examples work straight out of the box 👍
