### ISSUE TITLE
Multiple PySoundIo instances crash the program

### ISSUE THREAD

**Issue by m13253** [joextodd/pysoundio#32]
```python
>>> import pysoundio
>>> sio1 = pysoundio.PySoundIo(backend=pysoundio.SoundIoBackendAlsa)
>>> sio2 = pysoundio.PySoundIo(backend=pysoundio.SoundIoBackendJack)
>>> sio1._soundio
140182975315920
>>> sio2._soundio
140182972132512
>>> sio1.close()
>>> sio2.close()
'python3' terminated by signal SIGABRT (Abort)
```

The main reason of this problem is caused by the use of global variables in https://github.com/joextodd/pysoundio/blob/aca6ce52828885f620e259a530f6e63445854941/pysoundio/_soundiox.c#L347-L349

In the function `pysoundio__destroy`, the code calls `soundio_destroy` against the global variable `rc.soundio` instead of a handle passed from the Python layer, which is overwritten by consecutive `pysoundio__create` calls.
https://github.com/joextodd/pysoundio/blob/aca6ce52828885f620e259a530f6e63445854941/pysoundio/_soundiox.c#L396-L404

Similarly, PySoundIo will also crash if the user creates multiple streams, because the handles to the streams are also stored in global variables.

**Comment by joextodd** [comment]
Thanks for reporting this! This was a terrible design but I backed myself into a corner with the C-API a bit. #33 includes a migration to CFFI which will fix this issue as well as make it more efficient!

**Comment by m13253** [comment]
> Thanks for reporting this! This was a terrible design but I backed myself into a corner with the C-API a bit. #33 includes a migration to CFFI which will fix this issue as well as make it more efficient!

Indeed, global variables are the source of many bugs.

And I understand fixing this takes a great effort. So, Thank you for the fix!

I am looking forward to trying the new version! 👍
